[package]
name = "sandengine-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
colored = "2.0.4"
serde_yaml = "0.9.24"
thiserror = "1.0.44"
